### ISSUE TITLE
getting error while searching song

### ISSUE THREAD

**Issue by devsapariya94** [tanmay606/YouTubeMusicPythonAPI#2]
Traceback (most recent call last):
  File "test.py", line 170, in <module>
    x.ListVideos()
  File "test.py", line 64, in ListVideos
    self.EachVideo = WebDriverWait(self.Browser,5).until(EC.presence_of_element_located((By.XPATH,self.xpath)))
  File "C:\Users\Admin\Desktop\tests\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 181, in <module>
    except selenium.common.exceptions.WebDriverException:
NameError: name 'selenium' is not defined

geting the above error when i enter song name..

**Comment by tanmay606** [comment]
You need to have selenium library installed with python, do it with 'pip install selenium', and try again.
